### ISSUE TITLE
Exception when requesting textDocument/hover

### ISSUE THREAD

**Issue by rwols** [regen100/cmake-language-server#20]
Given the following cmake file: https://github.com/llvm/llvm-project/blob/master/libc/src/stdio/CMakeLists.txt

If I hover over `add_entrypoint_object`, I see the following exception:

```
cmake: ERROR:pygls.protocol:Failed to handle request 2 textDocument/hover Object(position=Object(character=7, line=0), textDocument=Object(uri='file:///home/raoul/Documents/Programming/llvm-project/libc/src/stdio/CMakeLists.txt'))
:: --> cmake textDocument/hover(2): {'position': {'character': 7, 'line': 0}, 'textDocument': {'uri': 'file:///home/raoul/Documents/Programming/llvm-project/libc/src/stdio/CMakeLists.txt'}}
cmake: Traceback (most recent call last):
:: <~~ cmake 2: {'message': "AttributeError: 'NoneType' object has no attribute 'get_command_doc'", 'code': -32602, 'data': '{\'traceback\': [\'  File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/pygls/protocol.py", line 317, in _handle_request\\n    self._execute_request(msg_id, handler, params)\\n\', \'  File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/pygls/protocol.py", line 242, in _execute_request\\n    self._send_response(msg_id, handler(params))\\n\', \'  File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/cmake_language_server/server.py", line 142, in hover\\n    doc = c(word[0])\\n\', \'  File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/cmake_language_server/server.py", line 136, in <lambda>\\n    lambda x: self._api.get_command_doc(x.lower()),\\n\']}'}
cmake:   File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/pygls/protocol.py", line 317, in _handle_request
cmake:     self._execute_request(msg_id, handler, params)
cmake:   File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/pygls/protocol.py", line 242, in _execute_request
cmake:     self._send_response(msg_id, handler(params))
cmake:   File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/cmake_language_server/server.py", line 142, in hover
cmake:     doc = c(word[0])
cmake:   File "/home/raoul/.config/sublime-text-3/Cache/LSP-cmake/lib/python3.8/site-packages/cmake_language_server/server.py", line 136, in <lambda>
cmake:     lambda x: self._api.get_command_doc(x.lower()),
cmake: AttributeError: 'NoneType' object has no attribute 'get_command_doc'
```

Editor: Sublime Text with LSP plugin
cmake-language-server version: 0.1.2

**Comment by rwols** [comment]
Looks like I did not have this `buildDirectory` setting in my initializationOptions.

**Comment by rwols** [comment]
It would be a good idea to return a JSON-RPC error response if an exception occurs during handling of a request (perhaps this is better suited for pygls).
