### ISSUE TITLE
Broken, module not found for 'attrs' package even with attrs installed.

### ISSUE THREAD

**Issue by fcodes0** [regen100/cmake-language-server#74]
Not able to run. I continue to see this error even after installing attrs package.
```
Traceback (most recent call last):
  File "/home/frank/.local/bin/cmake-language-server", line 5, in <module>
    from cmake_language_server.server import main
  File "/home/frank/.local/lib/python3.10/site-packages/cmake_language_server/server.py", line 8, in <module>
    from lsprotocol.types import (
  File "/home/frank/.local/lib/python3.10/site-packages/lsprotocol/types.py", line 14, in <module>
    import attrs
ModuleNotFoundError: No module named 'attrs'
```

**Comment by svavs** [comment]
Running `pip3 install --user --upgrade attrs` fixed the issue for me.
