### ISSUE TITLE
cmakels error with emacs

### ISSUE THREAD

**Issue by sllvm** [regen100/cmake-language-server#80]
I have configured emacs to talk with cmake-language-server for lsp completion. Below, is the error which I get stderr.log. Please let me know how to resolve this issue. The error is continuously occuring, after I open a CMakeLists.txt for editing.

Installed server through macports. 

`sudo port install cmake-language-server
`
**emacs config is as follows..**

`(use-package cmake-mode
    :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'")
    :hook (cmake-mode . lsp-deferred))

  (use-package cmake-font-lock
    :after cmake-mode
    :config (cmake-font-lock-activate))
`
**stderr.log file**
Traceback (most recent call last):
  File "/opt/local/bin/cmake-language-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmake_language_server/server.py", line 263, in main
    CMakeLanguageServer("cmake-language-server", __version__).start_io()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmake_language_server/server.py", line 65, in __init__
    @self.feature(
     ^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygls/feature_manager.py", line 174, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/completion" should be instance of type <class 'lsprotocol.types.CompletionOptions'>

Process cmakels stderr finished

**Comment by jabra11** [comment]
same issue using nvim lsp

**Comment by 0xzer0x** [comment]
I think this is due to incompatibility with `pygls` module. Simply installing `pygls` module version 1.0.2 in the package venv solved the issue for me. I used the command `pip install pygls==1.0.2`

**Comment by atuleu** [comment]
Had the same issue on Pop OS 22.04. With `pygls==1.1.0` I have the same error, reverting to `1.0.2` solved the issue. Could you had a dependency on `pygls<1.1.0,>=1.0.0` ?
