### ISSUE TITLE
Error: typeguard.TypeCheckError: lsprotocol.types.TextDocumentSaveRegistrationOptions is not an instance of lsprotocol.types.SaveOptions

### ISSUE THREAD

**Issue by tonal** [regen100/cmake-language-server#81]
python version 3.11.5
```
$ pip install cmake-language-server
$ cmake-language-server
Traceback (most recent call last):
  File "cmake-language-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/cmake_language_server/server.py", line 263, in main
    CMakeLanguageServer("cmake-language-server", __version__).start_io()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/cmake_language_server/server.py", line 207, in __init__
    @self.feature(
     ^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/pygls/feature_manager.py", line 192, in decorator
    if options_type and not is_instance(options, options_type):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/pygls/lsp/__init__.py", line 136, in is_instance
    check_type(o, t)
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/typeguard/_functions.py", line 74, in check_type
    check_type_internal(value, expected_type, memo)
  File "/home/user/.pyenv/versions/3.11.5/envs/cmake-language-server-dir/lib/python3.11/site-packages/typeguard/_checkers.py", line 680, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: lsprotocol.types.TextDocumentSaveRegistrationOptions is not an instance of lsprotocol.types.SaveOptions
```
```
$ pip list 
Package               Version
--------------------- ----------
attrs                 23.1.0
build                 1.0.3
cattrs                23.1.2
click                 8.1.7
cmake-language-server 0.1.7
lsprotocol            2023.0.0b1
packaging             23.2
pip                   23.2.1
pip-tools             7.3.0
pygls                 1.1.0
pyproject_hooks       1.0.0
setuptools            68.2.2
typeguard             3.0.2
wheel                 0.41.2
```

**Comment by nega0** [comment]
it's because of pygls v1.1.0. `pip install 'pygls<1.1'`
