### ISSUE TITLE
Error Upon running the cmake-language-server binary

### ISSUE THREAD

**Issue by Aziz-repo** [regen100/cmake-language-server#86]
I intalled the package in my system using pip
I get the exception upon running the executable:

``` Traceback (most recent call last):
  File "/home/mohamed-aziz/.local/bin/cmake-language-server", line 8, in <module>
    sys.exit(main())
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/cmake_language_server/server.py", line 263, in main
    CMakeLanguageServer("cmake-language-server", __version__).start_io()  # type: ignore
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/cmake_language_server/server.py", line 212, in __init__
    def run_cmake(*args: Any) -> None:
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/pygls/feature_manager.py", line 192, in decorator
    if options_type and not is_instance(options, options_type):
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/pygls/lsp/__init__.py", line 136, in is_instance
    check_type(o, t)
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/typeguard/_functions.py", line 74, in check_type
    check_type_internal(value, expected_type, memo)
  File "/home/mohamed-aziz/.local/lib/python3.8/site-packages/typeguard/_checkers.py", line 680, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: lsprotocol.types.TextDocumentSaveRegistrationOptions is not an instance of lsprotocol.types.SaveOptions ```

**Comment by vsguzev** [comment]
Duplicate of [https://github.com/regen100/cmake-language-server/issues/81](https://github.com/regen100/cmake-language-server/issues/81)

**Comment by regen100** [comment]
Version 0.1.8, which uses the latest pygls, has been released
