### ISSUE TITLE
Has this been tested with vim-lsp?

### ISSUE THREAD

**Issue by Rubonnek** [regen100/cmake-language-server#9]
https://github.com/prabirshrestha/vim-lsp

I'm trying to get it to work, I just don't know how :p

**Comment by regen100** [comment]
I did not test it with `vim-lsp`. But I think it can work since it is based on the LSP specification.

**Comment by Rubonnek** [comment]
@regen100 would you mind taking a quick look at https://github.com/prabirshrestha/vim-lsp/issues/791?

I attempted to use it previously, but I'm missing a root_uri value I believe.

**Comment by Rubonnek** [comment]
Welp, I took a stab at this again and I got a crash on the server.

This is the message I got:

```
Fri 24 Apr 2020 09:18:07 PM EDT:["--->",1,"cmake",{"method":"textDocument/completion","on_notification":"---funcref---","params":{"textDocument":{"uri":"file:///home/wilson/gitrepos/development_tests/cpp_tests/opencv/CMakeLists.txt"},"position":{"character":1,"line":1}}}]
Fri 24 Apr 2020 09:18:07 PM EDT:["<---(stderr)",1,"cmake",["ERROR:pygls.protocol:Failed to handle request 2 textDocument/completion Object(textDocument=Object(uri='file:///home/wilson/gitrepos/development_tests/cpp_tests/opencv/CMakeLists.txt'), position=Object(character=1, line=1))","Traceback (most recent call last):","  File \"/usr/lib/python3.8/site-packages/pygls/protocol.py\", line 325, in _handle_request","    self._execute_request(msg_id, handler, params)","  File \"/usr/lib/python3.8/site-packages/pygls/protocol.py\", line 250, in _execute_request","    self._send_response(msg_id, handler(params))","  File \"/usr/lib/python3.8/site-packages/cmake_language_server/server.py\", line 45, in completions","    if (params.context.triggerKind ==","AttributeError: 'Object' object has no attribute 'context'",""]]
```

I got this message after updating the server with the master branch -- there's a python traceback within it:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pygls/protocol.py", line 325, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/usr/lib/python3.8/site-packages/pygls/protocol.py", line 250, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/usr/lib/python3.8/site-packages/cmake_language_server/server.py", line 45, in completions
    if (params.context.triggerKind ==
AttributeError: 'Object' object has no attribute 'context'
```

**Comment by Rubonnek** [comment]
For what is worth, this is the CMakeLists.txt I was using:

```cmake
cmake_minimum_required(VERSION 2.8)
project( DisplayImage )
find_package( OpenCV REQUIRED )
add_executable( LineExtraction lines_extraction.cpp )
target_link_libraries( LineExtraction ${OpenCV_LIBS} )
```

And I was attempting to auto complete 'add_library' so I just typed "add_" and attempted to auto complete.

**Comment by Rubonnek** [comment]
And here is the vim-lsp configuration I was using to register the server:

```vim
if executable('cmake-language-server')
	augroup lsp_cmake
		autocmd!
		autocmd User lsp_setup call lsp#register_server({
					\ 'name': 'cmake',
					\ 'cmd': {server_info->['cmake-language-server']},
					\ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'CMakeLists.txt'))},
					\ 'whitelist': [ 'CMakeLists.txt', 'cmake' ],
					\ 'initialization_options': {
					\   'buildDirectory': 'build',
					\ }})
	augroup end
endif
```

**Comment by regen100** [comment]
Thank you for the report! I will take a look.

**Comment by regen100** [comment]
I couldn't reproduce the problem.

```
$ docker run --rm -it ubuntu:18.04
# apt update && apt install -y vim cmake git python3-pip
# pip3 install cmake-language-server==0.1.1
# git clone https://github.com/prabirshrestha/vim-lsp.git
# git clone https://github.com/prabirshrestha/async.vim.git
# cat >~/.vimrc <<EOS
set runtimepath^=/vim-lsp,/async.vim
if executable('cmake-language-server')
  augroup lsp_cmake
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
      \ 'name': 'cmake',
      \ 'cmd': {server_info->['cmake-language-server']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'CMakeLists.txt'))},
      \ 'whitelist': [ 'CMakeLists.txt', 'cmake' ],
      \ 'initialization_options': {
      \   'buildDirectory': 'build',
      \ }})
  augroup end
endif
EOS
# cat >CMakeLists.txt <<EOS
cmake_minimum_required(VERSION 2.8)
project( DisplayImage )
find_package( OpenCV REQUIRED )
add_executable( LineExtraction lines_extraction.cpp )
target_link_libraries( LineExtraction ${OpenCV_LIBS} )
EOS
# vim CMakeLists.txt
```

`:LspStatus`, `:LspDocumentFormat`, and `:LspHover` worked correctly.

**Comment by Rubonnek** [comment]
Hmm... strange... I wonder if python3 is somehow broken under Arch Linux.

I'll keep investigating and report back if I see anything weird.

**Comment by regen100** [comment]
#11 seems to be related to this issue. The key point is the completion function. I did not test it so missed the problem.

**Comment by Rubonnek** [comment]
I'm still getting the exact same error after testing your patch.

**Comment by Rubonnek** [comment]
I'll try under an ubuntu 18.04 container and see if I can get it to work.

**Comment by Shatur95** [comment]
I tested and `:LspStatus` `:LspDocumentFormat` and `:LspHover` works as expected. But I do not have completion.
